In [24]:
import pandas as pd

In [25]:
ncaa = pd.read_csv('database.csv')

In [26]:
pd.options.display.max_columns = 60

In [27]:
# by conference
# by school 
# by sport
# by division

In [28]:
ncaa.head()

,SCHOOL_ID,SCHOOL_NAME,SCHOOL_TYPE,ACADEMIC_YEAR,SPORT_CODE,SPORT_NAME,NCAA_DIVISION,NCAA_SUBDIVISION,NCAA_CONFERENCE,FOURYEAR_ATHLETES,FOURYEAR_SCORE,FOURYEAR_ELIGIBILITY,FOURYEAR_RETENTION,2014_ATHLETES,2014_SCORE,2014_ELIGIBILITY,2014_RETENTION,2013_ATHLETES,2013_SCORE,2013_ELIGIBILITY,2013_RETENTION,2012_ATHLETES,2012_SCORE,2012_ELIGIBILITY,2012_RETENTION,2011_ATHLETES,2011_SCORE,2011_ELIGIBILITY,2011_RETENTION,2010_ATHLETES,2010_SCORE,2010_ELIGIBILITY,2010_RETENTION,2009_ATHLETES,2009_SCORE,2009_ELIGIBILITY,2009_RETENTION,2008_ATHLETES,2008_SCORE,2008_ELIGIBILITY,2008_RETENTION,2007_ATHLETES,2007_SCORE,2007_ELIGIBILITY,2007_RETENTION,2006_ATHLETES,2006_SCORE,2006_ELIGIBILITY,2006_RETENTION,2005_ATHLETES,2005_SCORE,2005_ELIGIBILITY,2005_RETENTION,2004_ATHLETES,2004_SCORE,2004_ELIGIBILITY,2004_RETENTION
0,100654,Alabama A&M University,0,2014,1,Baseball,1,2,Southwestern Athletic Conference,80,931,0.9020,0.9536,21,976,0.9762,0.9762,22,910,0.8718,0.9487,25,895,0.8542,0.9149,12,957,0.9167,1.0000,16,906,0.8750,0.9375,16,969,0.8438,1.0000,16,938,0.9375,0.9375,16,953,0.9063,1.0000,21,923,0.8974,0.9487,21,917,0.8810,0.9524,20,975,0.9750,0.9750
1,100654,Alabama A&M University,0,2014,4,Football,1,2,Southwestern Athletic Conference,321,932,0.8861,0.9613,78,905,0.8108,0.9797,86,933,0.9045,0.9548,78,940,0.8933,0.9597,79,951,0.9366,0.9507,69,931,0.9160,0.9375,74,935,0.9091,0.9466,64,930,0.9016,0.9500,75,919,0.8591,0.9799,70,941,0.9111,0.9630,74,921,0.8759,0.9655,74,871,0.8601,0.8811
2,100654,Alabama A&M University,0,2014,2,Men's Basketball,1,2,Southwestern Athletic Conference,43,964,0.9177,0.9880,12,958,0.9167,1.0000,10,975,0.9000,1.0000,8,1000,1.0000,1.0000,13,940,0.8800,0.9600,12,889,0.9565,0.8182,8,844,0.8750,0.8125,12,915,0.9167,0.9130,14,964,0.9643,0.9643,13,923,0.9615,0.8462,11,909,0.9091,0.9091,10,950,0.9500,0.9500
3,100654,Alabama A&M University,0,2014,6,Men's Golf,1,2,Southwestern Athletic Conference,22,898,0.7949,0.8462,4,1000,0.8750,1.0000,5,889,0.8889,0.8889,6,750,0.7000,0.8000,7,750,0.7500,0.7500,-99,-99,-99.0000,-99.0000,4,857,0.8571,0.8571,5,1000,0.9000,1.0000,4,1000,1.0000,1.0000,5,889,0.8889,0.8889,7,929,0.8571,1.0000,-99,-99,-99.0000,-99.0000
4,100654,Alabama A&M University,0,2014,13,Men's Tennis,1,2,Southwestern Athletic Conference,12,988,0.9130,1.0000,-99,-99,-99.0000,-99.0000,-99,-99,-99.0000,-99.0000,4,923,0.8571,1.0000,-99,-99,-99.0000,-99.0000,-99,-99,-99.0000,-99.0000,-99,-99,-99.0000,-99.0000,-99,-99,-99.0000,-99.0000,-99,-99,-99.0000,-99.0000,5,889,0.8889,0.8889,4,1000,1.0000,1.0000,6,958,1.0000,0.9167

In [29]:
ncaa.shape

(6511, 57)

In [30]:
ncaa.describe()

,SCHOOL_ID,SCHOOL_TYPE,ACADEMIC_YEAR,SPORT_CODE,NCAA_DIVISION,NCAA_SUBDIVISION,FOURYEAR_ATHLETES,FOURYEAR_SCORE,FOURYEAR_ELIGIBILITY,FOURYEAR_RETENTION,2014_ATHLETES,2014_SCORE,2014_ELIGIBILITY,2014_RETENTION,2013_ATHLETES,2013_SCORE,2013_ELIGIBILITY,2013_RETENTION,2012_ATHLETES,2012_SCORE,2012_ELIGIBILITY,2012_RETENTION,2011_ATHLETES,2011_SCORE,2011_ELIGIBILITY,2011_RETENTION,2010_ATHLETES,2010_SCORE,2010_ELIGIBILITY,2010_RETENTION,2009_ATHLETES,2009_SCORE,2009_ELIGIBILITY,2009_RETENTION,2008_ATHLETES,2008_SCORE,2008_ELIGIBILITY,2008_RETENTION,2007_ATHLETES,2007_SCORE,2007_ELIGIBILITY,2007_RETENTION,2006_ATHLETES,2006_SCORE,2006_ELIGIBILITY,2006_RETENTION,2005_ATHLETES,2005_SCORE,2005_ELIGIBILITY,2005_RETENTION,2004_ATHLETES,2004_SCORE,2004_ELIGIBILITY,2004_RETENTION
count,6511.000000,6511.000000,6511.0,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.00000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000,6511.000000
mean,179383.045769,0.352327,2014.0,19.440332,1.027185,-0.578252,76.191368,977.605130,0.809310,0.803183,18.225772,964.51390,-0.445785,-0.453462,15.971587,943.773460,-2.229515,-2.236134,15.315773,938.173552,-2.615341,-2.621492,14.426663,929.042390,-3.218220,-3.221734,14.049762,925.634618,-3.434158,-3.437863,12.950238,916.161880,-4.249431,-4.251718,10.579788,892.787590,-6.263177,-6.264764,8.902933,873.263093,-7.524736,-7.533149,7.581631,858.794962,-8.663151,-8.671093,4.334818,830.633697,-11.288113,-11.296628,3.214099,822.760559,-12.038817,-12.049140
std,41901.641274,0.477732,0.0,11.880657,0.179686,15.542044,63.082719,48.294332,4.106325,4.106059,21.272766,131.06603,11.864566,11.863650,26.113953,191.917651,17.624264,17.623062,26.998182,202.515238,18.611184,18.609996,28.222875,217.452922,20.038989,20.038248,28.657514,222.743720,20.523111,20.522307,30.271810,240.886392,22.242201,22.241654,34.054335,279.223889,25.898716,25.898264,36.039125,298.755627,27.870837,27.868270,37.922628,315.206358,29.491465,29.488868,41.367998,349.704347,32.783974,32.780792,42.105740,358.689463,33.630964,33.626971
min,100654.000000,0.000000,2014.0,1.000000,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.00000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,145813.000000,0.000000,2014.0,9.000000,1.000000,1.000000,39.000000,969.000000,0.968800,0.959200,10.000000,967.00000,0.970200,0.956500,10.000000,963.000000,0.962300,0.952400,10.000000,959.000000,0.960000,0.947400,10.000000,955.000000,0.951600,0.944400,9.000000,954.000000,0.950000,0.943250,9.000000,952.000000,0.946600,0.942000,9.000000,944.000000,0.937500,0.934800,9.000000,931.500000,0.928600,0.918900,8.000000,926.000000,0.922050,0.913000,8.000000,918.500000,0.916700,0.902900,8.000000,917.000000,0.916050,0.900000
50%,185828.000000,0.000000,2014.0,19.000000,1.000000,2.000000,58.000000,984.000000,0.985700,0.978000,15.000000,989.00000,1.000000,1.000000,15.000000,986.000000,1.000000,0.982800,15.000000,985.000000,1.000000,0.981500,15.000000,981.000000,1.000000,0.979200,14.000000,981.000000,1.000000,0.978300,14.000000,980.000000,1.000000,0.977300,14.000000,977.000000,0.982800,0.973700,14.000000,969.000000,0.979600,0.961500,14.000000,965.000000,0.975600,0.958300,13.000000,963.000000,0.970600,0.956500,13.000000,964.000000,0.975800,0.954600
75%,215770.000000,1.000000,2014.0,31.000000,1.000000,2.000000,94.000000,994.000000,1.000000,0.989800,24.000000,1000.00000,1.000000,1.000000,24.000000,1000.000000,1.000000,1.000000,24.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,22.000000,1000.000000,1.000000,1.000000,22.000000,1000.000000,1.000000,1.000000,21.000000,1000.000000,1.000000,1.000000,21.000000,1000.000000,1.000000,1.000000,20.000000,1000.000000,1.000000,1.000000
max,433660.000000,1.000000,2014.0,38.000000,3.000000,3.000000,452.000000,1000.000000,1.000000,1.000000,145.000000,1000.00000,1.000000,1.000000,112.000000,1000.000000,1.000000,1.000000,113.000000,1000.000000,1.000000,1.000000,114.000000,1000.000000,1.000000,1.000000,120.000000,1000.000000,1.000000,1.000000,121.000000,1000.000000,1.000000,1.000000,125.000000,1000.000000,1.000000,1.000000,129.000000,1000.000000,1.000000,1.000000,209.000000,1000.000000,1.000000,1.000000,179.000000,1000.000000,1.000000,1.000000,123.000000,1000.000000,1.000000,1.000000

In [31]:
ncaa.describe(include=['object'])

               SCHOOL_NAME        SPORT_NAME     NCAA_CONFERENCE
count                 6511              6511                6511
unique                 385                38                  48
top     Harvard University  Men's Basketball  Big Ten Conference
freq                    34               350                 341

In [32]:
ncaa.dtypes

SCHOOL_ID                 int64
SCHOOL_NAME              object
SCHOOL_TYPE               int64
ACADEMIC_YEAR             int64
SPORT_CODE                int64
SPORT_NAME               object
NCAA_DIVISION             int64
NCAA_SUBDIVISION          int64
NCAA_CONFERENCE          object
FOURYEAR_ATHLETES         int64
FOURYEAR_SCORE            int64
FOURYEAR_ELIGIBILITY    float64
FOURYEAR_RETENTION      float64
2014_ATHLETES             int64
2014_SCORE                int64
2014_ELIGIBILITY        float64
2014_RETENTION          float64
2013_ATHLETES             int64
2013_SCORE                int64
2013_ELIGIBILITY        float64
2013_RETENTION          float64
2012_ATHLETES             int64
2012_SCORE                int64
2012_ELIGIBILITY        float64
2012_RETENTION          float64
2011_ATHLETES             int64
2011_SCORE                int64
2011_ELIGIBILITY        float64
2011_RETENTION          float64
2010_ATHLETES             int64
2010_SCORE                int64
2010_ELIGIBILITY        float64
2010_RETENTION          float64
2009_ATHLETES             int64
2009_SCORE                int64
2009_ELIGIBILITY        float64
2009_RETENTION          float64
2008_ATHLETES             int64
2008_SCORE                int64
2008_ELIGIBILITY        float64
2008_RETENTION          float64
2007_ATHLETES             int64
2007_SCORE                int64
2007_ELIGIBILITY        float64
2007_RETENTION          float64
2006_ATHLETES             int64
2006_SCORE                int64
2006_ELIGIBILITY        float64
2006_RETENTION          float64
2005_ATHLETES             int64
2005_SCORE                int64
2005_ELIGIBILITY        float64
2005_RETENTION          float64
2004_ATHLETES             int64
2004_SCORE                int64
2004_ELIGIBILITY        float64
2004_RETENTION          float64
dtype: object

In [33]:
ncaa.isnull().sum()

SCHOOL_ID               0
SCHOOL_NAME             0
SCHOOL_TYPE             0
ACADEMIC_YEAR           0
SPORT_CODE              0
SPORT_NAME              0
NCAA_DIVISION           0
NCAA_SUBDIVISION        0
NCAA_CONFERENCE         0
FOURYEAR_ATHLETES       0
FOURYEAR_SCORE          0
FOURYEAR_ELIGIBILITY    0
FOURYEAR_RETENTION      0
2014_ATHLETES           0
2014_SCORE              0
2014_ELIGIBILITY        0
2014_RETENTION          0
2013_ATHLETES           0
2013_SCORE              0
2013_ELIGIBILITY        0
2013_RETENTION          0
2012_ATHLETES           0
2012_SCORE              0
2012_ELIGIBILITY        0
2012_RETENTION          0
2011_ATHLETES           0
2011_SCORE              0
2011_ELIGIBILITY        0
2011_RETENTION          0
2010_ATHLETES           0
2010_SCORE              0
2010_ELIGIBILITY        0
2010_RETENTION          0
2009_ATHLETES           0
2009_SCORE              0
2009_ELIGIBILITY        0
2009_RETENTION          0
2008_ATHLETES           0
2008_SCORE              0
2008_ELIGIBILITY        0
2008_RETENTION          0
2007_ATHLETES           0
2007_SCORE              0
2007_ELIGIBILITY        0
2007_RETENTION          0
2006_ATHLETES           0
2006_SCORE              0
2006_ELIGIBILITY        0
2006_RETENTION          0
2005_ATHLETES           0
2005_SCORE              0
2005_ELIGIBILITY        0
2005_RETENTION          0
2004_ATHLETES           0
2004_SCORE              0
2004_ELIGIBILITY        0
2004_RETENTION          0
dtype: int64

In [43]:
div1 = ncaa[ncaa['NCAA_DIVISION'] == 1]

In [34]:
cols = ['FOURYEAR_SCORE', '2014_SCORE', '2013_SCORE', '2012_SCORE', '2011_SCORE', '2010_SCORE', '2009_SCORE',
       '2008_SCORE', '2007_SCORE', '2006_SCORE', '2005_SCORE', '2004_SCORE']

In [92]:
ncaa.groupby('SCHOOL_NAME')[cols].mean().sort_values('FOURYEAR_SCORE', ascending=False).reset_index()

,SCHOOL_NAME,FOURYEAR_SCORE,2014_SCORE,2013_SCORE,2012_SCORE,2011_SCORE,2010_SCORE,2009_SCORE,2008_SCORE,2007_SCORE,2006_SCORE,2005_SCORE,2004_SCORE
0,Merrimack College,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,989.000000,939.000000,938.000000,940.000000,956.000000,978.000000
1,Massachusetts Institute of Technology,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,-99.000000,-99.000000,-99.000000
2,Dartmouth College,999.107143,998.285714,999.285714,1000.000000,998.857143,995.357143,998.321429,996.000000,994.428571,996.321429,997.642857,991.607143
3,Colorado College,998.500000,988.000000,1000.000000,1000.000000,993.000000,987.000000,1000.000000,988.500000,994.500000,974.500000,1000.000000,994.000000
4,Rensselaer Polytechnic Institute,998.500000,1000.000000,1000.000000,994.000000,1000.000000,987.000000,994.000000,1000.000000,993.000000,1000.000000,450.500000,450.500000
5,Gonzaga University,997.647059,997.117647,999.235294,999.058824,865.647059,860.176471,861.352941,856.823529,862.117647,601.470588,602.529412,593.588235
6,Rochester Institute of Technology,997.500000,995.500000,994.500000,450.500000,450.500000,450.500000,443.500000,440.000000,440.500000,407.000000,-99.000000,-99.000000
7,Northwestern University,997.263158,994.736842,997.894737,996.842105,997.789474,991.736842,995.210526,993.947368,990.368421,988.052632,978.631579,991.315789
8,Ferris State University,997.000000,979.000000,1000.000000,1000.000000,989.000000,977.000000,1000.000000,989.000000,957.000000,967.000000,967.000000,976.000000
9,Bentley University,997.000000,1000.000000,1000.000000,1000.000000,988.000000,986.000000,1000.000000,1000.000000,972.000000,984.000000,985.000000,1000.000000
10,Colgate University,996.500000,994.666667,950.083333,995.583333,998.000000,992.041667,948.875000,947.083333,994.041667,991.458333,707.541667,763.125000
11,Stanford University,995.967742,927.483871,919.483871,924.548387,958.548387,955.000000,982.483871,988.677419,989.000000,954.258065,919.096774,911.419355
12,Brown University,995.909091,996.303030,996.787879,995.909091,993.787879,997.030303,992.151515,992.969697,992.787879,991.909091,996.484848,995.121212
13,University of Notre Dame,995.730769,995.576923,994.730769,995.807692,994.692308,991.346154,995.923077,997.461538,990.923077,990.692308,993.653846,991.461538
14,Johns Hopkins University,995.500000,991.000000,1000.000000,992.000000,1000.000000,982.000000,989.000000,984.500000,1000.000000,987.500000,1000.000000,984.500000
15,Yale University,995.344828,995.379310,994.172414,996.896552,994.896552,996.379310,995.862069,998.689655,998.448276,998.103448,996.965517,999.827586
16,Davidson College,995.095238,944.857143,836.285714,996.809524,990.238095,997.809524,994.428571,993.285714,988.000000,996.523810,989.190476,990.238095
17,Duke University,995.038462,911.961538,866.961538,869.153846,865.884615,863.384615,912.769231,949.692308,992.576923,858.769231,863.346154,863.923077
18,Loyola University Chicago,994.866667,993.266667,996.800000,993.800000,995.400000,987.266667,996.333333,993.600000,988.533333,974.933333,975.000000,984.933333
19,University of Pennsylvania,994.750000,989.714286,997.678571,994.535714,993.142857,990.607143,992.178571,995.821429,997.750000,991.214286,987.178571,996.071429
20,College of the Holy Cross,994.730769,828.230769,868.846154,948.269231,781.807692,827.538462,780.730769,827.423077,821.076923,863.076923,783.961538,822.500000
21,Georgetown University,994.045455,941.772727,893.772727,942.772727,944.772727,894.500000,889.227273,841.454545,737.227273,894.181818,836.181818,742.227273
22,Union College (New York),994.000000,1000.000000,981.500000,995.000000,1000.000000,994.000000,984.500000,989.000000,957.500000,991.000000,446.000000,446.000000
23,Columbia University-Barnard College,993.923077,995.076923,993.115385,991.230769,996.038462,986.269231,994.538462,992.423077,988.692308,989.807692,991.384615,989.692308
24,Bucknell University,993.814815,872.555556,868.518519,831.000000,873.481481,917.370370,831.629630,789.185185,708.185185,629.888889,662.074074,626.888889
25,Vanderbilt University,993.500000,921.375000,924.312500,925.437500,922.250000,920.750000,929.062500,854.625000,848.937500,845.437500,833.062500,706.125000
26,"University of Minnesota, Twin Cities",993.480000,994.320000,996.680000,994.760000,985.000000,978.360000,980.840000,981.960000,976.040000,966.200000,962.440000,979.520000
27,Elon University,993.470588,995.411765,932.705882,923.294118,927.235294,925.470588,926.411765,919.294118,914.882353,915.411765,917.352941,909.647059
28,Fairfield University,993.052632,993.473684,987.526316,933.842105,933.000000,935.736842,923.157895,750.315789,691.473684,931.947368,927.210526,696.526316
29,American International College,993.000000,1000.000000,986.000000,987.000000,1000.000000,984.000000,982.000000,967.000000,1000.000000,982.000000,1000.000000,1000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,Texas Southern University,953.562500,969.812500,953.937500,963.187500,918.812500,859.437500,737.312500,713.437500,771.500000,888.875000,818.000000,868.437500
356,Morgan State University,952.071429,948.642857,934.000000,942.714286,882.571429,961.785714,951.500000,962.285714,937.571429,947.214286,934.428571,958.928571
357,Bloomsburg University of Pennsylvania,952.000000,967.000000,936.000000,983.000000,926.000000,944.000000,931.000000,952.000000,983.000000,952.000000,953.000000,903.000000
358,Edinboro University of Pennsylvania,952.000000,969.000000,964.000000,936.000000,926.000000,930.000000,947.000000,919.000000,985.000000,974.000000,939.000000,934.000000
359,"California State University, Bakersfield",951.647059,960.117647,945.176471,951.941176,935.588235,924.882353,955.058824,865.705882,767.764706,-39.588235,-41.941176,-35.117647
360,Coppin State University,951.571429,985.928571,955.142857,843.428571,692.285714,696.428571,867.857143,885.142857,779.785714,953.357143,950.500000,918.142857
361,"University of Arkansas, Pine Bluff",950.750000,827.875000,824.875000,861.750000,891.687500,787.625000,877.812500,695.312500,755.375000,743.500000,761.187500,811.687500
362,Alabama State University,950.444444,957.055556,950.500000,944.722222,929.444444,922.944444,907.777778,901.000000,934.055556,906.777778,794.944444,856.555556
363,Grambling State University,949.733333,937.266667,947.533333,929.266667,894.133333,888.266667,947.533333,913.600000,968.266667,925.200000,935.600000,926.466667
364,North Carolina A&T State University,949.000000,961.000000,881.133333,945.266667,859.866667,851.333333,903.933333,939.800000,676.533333,933.133333,953.666667,934.800000
365,Francis Marion University,949.000000,965.500000,1000.000000,946.000000,872.500000,949.000000,1000.000000,1000.000000,945.000000,931.000000,-99.000000,-99.000000
366,University of Maryland Eastern Shore,948.933333,836.133333,779.666667,809.600000,726.666667,732.133333,760.000000,740.333333,800.400000,733.666667,867.133333,794.600000
367,University of Alabama in Huntsville,948.000000,959.000000,957.000000,978.000000,908.000000,943.000000,957.000000,980.000000,947.000000,940.000000,940.000000,958.000000
368,Prairie View A&M University,947.777778,932.500000,822.888889,953.611111,920.666667,925.722222,877.833333,832.166667,938.555556,939.166667,848.833333,910.555556
369,University of New Orleans,943.428571,918.642857,662.000000,299.214286,276.642857,409.214286,412.428571,266.785714,261.571429,265.785714,903.642857,852.214286
370,Fordham University,940.047619,945.809524,940.047619,935.190476,938.095238,930.714286,941.190476,940.476190,880.476190,929.619048,879.904762,879.571429
371,New York Institute of Technology,935.000000,930.000000,936.000000,946.000000,930.000000,990.000000,959.000000,1000.000000,969.000000,967.000000,942.000000,909.000000
372,University of North Dakota,933.380952,877.619048,929.142857,934.523810,931.047619,915.714286,915.190476,3.523810,3.952381,-0.619048,-2.142857,-48.571429
373,Wofford College,932.166667,872.611111,927.722222,934.888889,928.944444,931.555556,931.388889,928.111111,925.888889,929.500000,742.944444,904.111111
374,Norfolk State University,932.000000,955.200000,957.933333,925.733333,885.066667,881.533333,900.466667,915.466667,930.400000,863.800000,853.533333,857.933333
375,Clarion University of Pennsylvania,932.000000,942.000000,923.000000,913.000000,941.000000,949.000000,946.000000,967.000000,889.000000,875.000000,820.000000,920.000000
376,Florida A&M University,931.937500,895.625000,956.187500,914.750000,946.750000,848.562500,916.375000,877.562500,879.875000,975.625000,910.750000,912.375000
377,Savannah State University,930.266667,899.533333,932.200000,935.666667,914.666667,697.200000,729.600000,736.866667,790.333333,710.600000,720.133333,807.333333
378,University of the Incarnate Word,925.150000,894.750000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
379,Cleveland State University,923.058824,930.235294,923.647059,853.647059,785.470588,788.529412,791.058824,781.823529,823.647059,767.941176,690.823529,698.941176
380,Grand Canyon University,922.047619,894.761905,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
381,Drake University,918.500000,917.055556,918.222222,916.388889,920.166667,927.222222,920.444444,908.333333,972.944444,844.277778,921.555556,908.777778
382,Tulane University,916.466667,919.466667,841.933333,767.066667,767.200000,769.666667,619.666667,473.333333,484.066667,400.733333,898.533333,840.666667
383,Jacksonville University,912.470588,899.764706,920.235294,906.529412,912.823529,901.294118,783.705882,764.470588,763.470588,778.764706,752.352941,749.117647
384,Lafayette College,901.391304,855.260870,805.608696,805.913043,852.173913,853.913043,756.565217,750.391304,803.173913,706.130435,753.695652,797.434783

In [15]:
ncaa[ncaa['SCHOOL_NAME'] == 'Merrimack College']

,SCHOOL_ID,SCHOOL_NAME,SCHOOL_TYPE,ACADEMIC_YEAR,SPORT_CODE,SPORT_NAME,NCAA_DIVISION,NCAA_SUBDIVISION,NCAA_CONFERENCE,FOURYEAR_ATHLETES,FOURYEAR_SCORE,FOURYEAR_ELIGIBILITY,FOURYEAR_RETENTION,2014_ATHLETES,2014_SCORE,2014_ELIGIBILITY,2014_RETENTION,2013_ATHLETES,2013_SCORE,2013_ELIGIBILITY,2013_RETENTION,2012_ATHLETES,2012_SCORE,2012_ELIGIBILITY,2012_RETENTION,2011_ATHLETES,2011_SCORE,2011_ELIGIBILITY,2011_RETENTION,2010_ATHLETES,2010_SCORE,2010_ELIGIBILITY,2010_RETENTION,2009_ATHLETES,2009_SCORE,2009_ELIGIBILITY,2009_RETENTION,2008_ATHLETES,2008_SCORE,2008_ELIGIBILITY,2008_RETENTION,2007_ATHLETES,2007_SCORE,2007_ELIGIBILITY,2007_RETENTION,2006_ATHLETES,2006_SCORE,2006_ELIGIBILITY,2006_RETENTION,2005_ATHLETES,2005_SCORE,2005_ELIGIBILITY,2005_RETENTION,2004_ATHLETES,2004_SCORE,2004_ELIGIBILITY,2004_RETENTION
2668,166850,Merrimack College,1,2014,8,Men's Ice Hockey,2,-99,Northeast-10 Conference,92,1000,1.0,1.0,23,1000,1.0,1.0,24,1000,1.0,1.0,22,1000,1.0,1.0,23,1000,1.0,1.0,22,1000,1.0,1.0,25,989,0.9796,1.0,25,939,0.94,0.9375,21,938,0.95,0.925,26,940,0.96,0.92,23,956,0.9556,0.9556,23,978,0.9778,0.9778

In [95]:
div1.groupby('SCHOOL_NAME')[['NCAA_CONFERENCE', 'FOURYEAR_SCORE']
                           ].mean().sort_values('FOURYEAR_SCORE', ascending=False).reset_index()[0:10]

                SCHOOL_NAME  FOURYEAR_SCORE
0         Dartmouth College      999.107143
1        Gonzaga University      997.647059
2   Northwestern University      997.263158
3        Colgate University      996.500000
4       Stanford University      995.967742
5          Brown University      995.909091
6  University of Notre Dame      995.730769
7           Yale University      995.344828
8          Davidson College      995.095238
9           Duke University      995.038462

In [47]:
div1.groupby(['SCHOOL_NAME', 'SPORT_NAME'])[cols].mean().sort_values('2014_SCORE', ascending=False).reset_index()

,SCHOOL_NAME,SPORT_NAME,FOURYEAR_SCORE,2014_SCORE,2013_SCORE,2012_SCORE,2011_SCORE,2010_SCORE,2009_SCORE,2008_SCORE,2007_SCORE,2006_SCORE,2005_SCORE,2004_SCORE
0,Loyola Marymount University,Women's Soccer,990,1000,1000,975,987,978,1000,988,962,986,987,1000
1,University of North Carolina Wilmington,Women's Volleyball,994,1000,1000,1000,975,1000,1000,974,1000,955,962,1000
2,Nicholls State University,Women's Cross Country,993,1000,1000,962,1000,969,962,1000,905,824,909,875
3,Nicholls State University,"Women's Track, Indoor",951,1000,931,902,975,965,978,947,921,844,847,848
4,University of North Carolina Wilmington,Women's Tennis,1000,1000,1000,1000,1000,1000,1000,958,864,1000,1000,929
5,University of North Carolina Wilmington,Women's Golf,974,1000,917,969,1000,1000,1000,1000,1000,1000,955,950
6,University of North Carolina Wilmington,Women's Cross Country,981,1000,952,1000,974,1000,1000,1000,955,950,-99,-99
7,Norfolk State University,Women's Bowling,978,1000,1000,944,929,861,923,1000,857,-99,-99,-99
8,University of North Carolina Wilmington,Men's Tennis,992,1000,1000,969,1000,968,1000,1000,958,1000,893,964
9,University of North Carolina Wilmington,Men's Soccer,996,1000,1000,985,1000,974,939,988,859,986,974,976
10,University of North Carolina Wilmington,Men's Golf,992,1000,967,1000,971,964,1000,1000,923,900,972,1000
11,University of North Carolina Wilmington,Men's Cross Country,997,1000,-99,964,-99,938,-99,-99,861,1000,1000,-99
12,University of North Carolina Wilmington,Men's Basketball,958,1000,1000,980,821,865,920,940,976,1000,1000,981
13,University of North Carolina Wilmington,Baseball,1000,1000,981,1000,1000,980,1000,968,911,949,935,984
14,University of North Carolina Asheville,"Women's Track, Outdoor",1000,1000,1000,1000,1000,984,1000,1000,926,894,908,1000
15,University of North Carolina Asheville,"Women's Track, Indoor",996,1000,987,1000,1000,984,1000,1000,926,935,897,1000
16,North Carolina A&T State University,Women's Basketball,947,1000,942,963,879,911,893,980,977,893,857,891
17,North Carolina A&T State University,Women's Bowling,998,1000,1000,944,1000,-99,833,850,938,889,938,1000
18,University of North Carolina Asheville,Women's Tennis,1000,1000,1000,1000,1000,1000,1000,1000,1000,962,962,962
19,North Carolina A&T State University,Women's Swimming,976,1000,1000,953,942,880,917,917,1000,942,958,932
20,North Carolina A&T State University,Women's Tennis,924,1000,813,1000,1000,968,917,1000,1000,1000,969,857
21,University of North Carolina Asheville,Women's Cross Country,994,1000,980,1000,1000,1000,1000,1000,955,929,903,1000
22,North Carolina A&T State University,Women's Volleyball,952,1000,1000,964,864,943,925,944,1000,975,1000,750
23,North Carolina Central University,Baseball,991,1000,989,1000,976,969,927,938,-99,-99,-99,-99
24,University of North Carolina Asheville,Women's Basketball,1000,1000,982,1000,1000,963,961,940,962,944,981,964
25,Nicholls State University,Men's Tennis,982,1000,938,1000,1000,929,875,1000,909,833,857,-99
26,University of North Carolina at Greensboro,Men's Golf,983,1000,1000,968,929,944,865,900,1000,969,1000,1000
27,Northern Illinois University,Women's Tennis,977,1000,1000,1000,900,974,1000,900,1000,962,1000,950
28,University of North Carolina at Greensboro,Men's Soccer,963,1000,982,1000,878,841,975,943,976,1000,936,987
29,"University of North Carolina, Chapel Hill",Men's Cross Country,994,1000,1000,977,1000,1000,962,1000,941,955,933,958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6323,"University of Arkansas, Little Rock",Women's Tennis,987,-99,955,897,1000,909,935,1000,938,1000,1000,1000
6324,Pepperdine University,Men's Cross Country,994,-99,-99,-99,-99,938,900,929,-99,955,938,-99
6325,University of Hartford,"Men's Track, Indoor",1000,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
6326,Texas Christian University,Women's Cross Country,994,-99,964,1000,952,1000,958,1000,1000,964,1000,944
6327,University of Hartford,Men's Cross Country,1000,-99,-99,-99,-99,-99,-99,-99,-99,962,1000,938
6328,Stony Brook University,Men's Swimming,939,-99,833,938,969,954,864,958,1000,982,968,935
6329,University of Southern California,Women's Cross Country,1000,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
6330,University of North Carolina at Greensboro,Men's Cross Country,1000,-99,-99,1000,1000,1000,1000,1000,1000,821,-99,925
6331,Nicholls State University,Men's Cross Country,994,-99,1000,968,968,1000,870,875,909,778,1000,765
6332,Stanford University,Men's Fencing,993,-99,-99,-99,1000,1000,840,938,1000,1000,-99,-99
6333,Stanford University,Women's Fencing,1000,-99,-99,-99,-99,-99,1000,938,1000,-99,-99,-99
6334,University of Miami (Florida),Men's Swimming,1000,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
6335,College of William and Mary,Men's Gymnastics,993,-99,-99,-99,966,1000,-99,1000,-99,1000,-99,-99
6336,Drake University,Women's Rowing,-99,-99,-99,-99,-99,-99,-99,-99,1000,-99,987,965
6337,University of North Dakota,Men's Golf,992,-99,900,1000,1000,964,1000,-99,-99,-99,-99,-99
6338,Duke University,Men's Swimming,1000,-99,-99,-99,-99,-99,1000,1000,992,989,1000,992
6339,Vanderbilt University,Men's Cross Country,1000,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
6340,Stetson University,Men's Cross Country,1000,-99,1000,1000,1000,1000,875,950,917,929,1000,917
6341,Villanova University,Women's Water Polo,1000,-99,1000,-99,-99,-99,981,1000,947,-99,-99,1000
6342,Providence College,Women's Tennis,1000,-99,1000,1000,-99,-99,-99,-99,-99,-99,1000,967
6343,Tulane University,Men's Cross Country,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1000,1000
6344,Ball State University,Men's Swimming,994,-99,-99,986,1000,1000,968,985,987,1000,979,1000
6345,Villanova University,Women's Tennis,1000,-99,-99,1000,-99,1000,-99,-99,971,-99,-99,979
6346,Wofford College,Mixed Rifle,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
6347,Duke University,Women's Fencing,1000,-99,-99,-99,-99,-99,-99,1000,1000,1000,1000,1000
6348,University of North Dakota,Men's Tennis,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
6349,Hampton University,Men's Tennis,997,-99,950,1000,1000,1000,938,700,950,1000,1000,1000
6350,Hampton University,Men's Golf,985,-99,950,1000,889,929,1000,1000,900,893,850,1000
6351,Wofford College,Men's Cross Country,993,-99,900,1000,1000,1000,1000,1000,1000,1000,-99,929
6352,"California State University, Northridge",Men's Cross Country,990,-99,900,-99,-99,-99,-99,-99,1000,875,875,938

In [37]:
ncaa.groupby('SPORT_NAME')[cols].mean().sort_values('2014_SCORE', ascending=False).reset_index()

,SPORT_NAME,FOURYEAR_SCORE,2014_SCORE,2013_SCORE,2012_SCORE,2011_SCORE,2010_SCORE,2009_SCORE,2008_SCORE,2007_SCORE,2006_SCORE,2005_SCORE,2004_SCORE
0,Men's Skiing,983.090909,993.727273,976.909091,980.000000,879.000000,977.909091,871.636364,966.000000,969.454545,966.727273,959.454545,874.090909
1,Women's Ice Hockey,989.914286,992.114286,958.600000,926.371429,925.400000,928.342857,925.628571,892.685714,887.142857,853.057143,700.200000,729.314286
2,Women's Gymnastics,990.983607,991.721311,993.049180,987.114754,987.377049,990.278689,988.262295,987.098361,984.393443,980.442623,963.803279,964.377049
3,Women's Lacrosse,989.961165,990.174757,957.368932,881.961165,861.407767,838.077670,820.786408,775.300971,732.951456,721.495146,689.106796,667.757282
4,Men's Volleyball,984.818182,988.590909,936.045455,927.045455,928.681818,934.000000,928.181818,877.500000,879.000000,813.909091,774.545455,759.272727
5,Women's Field Hockey,988.230769,988.500000,970.589744,973.589744,961.653846,962.076923,948.923077,933.794872,927.192308,913.307692,901.102564,885.205128
6,Women's Soccer,984.297872,985.990881,960.717325,956.577508,951.908815,949.528875,940.185410,922.279635,905.832827,886.762918,854.392097,848.726444
7,Men's Ice Hockey,985.237288,985.966102,984.694915,966.745763,963.932203,963.813559,962.203390,961.847458,952.983051,948.016949,935.355932,916.966102
8,Women's Volleyball,983.729730,985.678679,968.588589,964.447447,956.513514,956.156156,953.516517,932.720721,914.018018,898.261261,880.009009,877.936937
9,Women's Skiing,987.750000,983.500000,991.416667,988.916667,981.166667,993.916667,985.833333,878.333333,998.416667,958.916667,879.750000,888.750000
10,"Women's Track, Outdoor",981.900302,982.924471,954.649547,950.353474,932.761329,931.410876,922.244713,899.374622,891.673716,876.018127,840.567976,827.024169
11,Women's Softball,981.255973,981.576792,967.928328,956.105802,953.191126,951.726962,940.880546,916.730375,891.402730,869.129693,838.563140,838.730375
12,Women's Basketball,975.793103,980.043103,962.063218,958.660920,953.327586,951.442529,947.764368,929.692529,913.867816,900.804598,879.402299,877.250000
13,Women's Swimming,988.131980,978.817259,959.670051,960.218274,957.111675,949.192893,940.604061,893.365482,891.741117,869.375635,859.578680,847.837563
14,"Women's Track, Indoor",980.425000,978.753125,945.890625,947.821875,935.921875,935.018750,928.728125,895.993750,877.828125,864.146875,848.728125,838.940625
15,Women's Golf,991.600760,975.946768,957.581749,932.547529,913.418251,910.539924,884.718631,850.380228,796.361217,784.832700,747.380228,727.840304
16,Men's Soccer,971.660099,975.068966,954.812808,949.310345,939.714286,942.802956,931.093596,915.201970,891.344828,874.192118,849.103448,849.453202
17,Men's Wrestling,964.467532,969.103896,923.103896,936.610390,928.974026,931.974026,916.350649,935.818182,904.532468,887.922078,828.415584,834.896104
18,Baseball,969.266667,968.590000,954.123333,944.643333,943.203333,943.500000,931.886667,913.010000,881.650000,868.230000,839.046667,833.596667
19,Women's Cross Country,987.991329,965.372832,943.378613,941.280347,946.855491,948.124277,913.979769,901.872832,894.043353,883.450867,843.317919,838.404624
20,Men's Basketball,961.480000,964.160000,951.842857,945.108571,931.765714,931.817143,927.594286,910.348571,883.482857,870.080000,852.337143,850.085714
21,Football,956.293173,962.004016,937.987952,932.413655,915.449799,908.594378,906.088353,888.485944,874.489960,862.867470,848.100402,843.783133
22,Men's Lacrosse,978.358209,961.731343,897.014925,864.985075,859.626866,828.820896,812.686567,780.940299,763.970149,762.656716,764.805970,713.014925
23,"Men's Track, Indoor",969.212355,961.131274,911.822394,923.876448,911.034749,913.718147,913.127413,868.934363,844.849421,823.679537,800.861004,787.328185
24,Women's Tennis,988.962733,960.279503,950.347826,950.118012,922.428571,919.456522,925.555901,892.012422,864.885093,866.263975,835.804348,853.832298
25,"Men's Track, Outdoor",971.032143,955.982143,936.514286,933.950000,916.482143,919.892857,915.221429,892.592857,872.185714,848.296429,812.550000,785.782143
26,Women's Water Polo,988.468750,954.718750,990.906250,948.156250,918.375000,911.437500,947.156250,948.062500,930.187500,832.593750,771.562500,810.593750
27,Men's Golf,980.264901,952.973510,934.225166,933.400662,922.513245,904.870861,893.894040,867.115894,859.384106,852.721854,806.387417,793.407285
28,Men's Water Polo,985.772727,942.454545,931.136364,930.727273,932.090909,934.545455,878.590909,877.636364,823.409091,814.681818,779.818182,727.727273
29,Men's Swimming,979.540741,939.348148,915.422222,939.051852,928.022222,917.911111,918.570370,892.014815,884.148148,845.962963,830.592593,829.970370
30,Women's Rowing,975.931034,938.816092,925.195402,898.597701,885.781609,897.827586,896.735632,861.011494,837.045977,798.045977,791.632184,785.000000
31,Men's Tennis,978.222222,937.295019,925.444444,924.233716,911.862069,900.636015,891.241379,867.141762,840.551724,836.352490,830.318008,810.766284
32,Women's Bowling,985.781250,932.781250,976.062500,908.593750,875.218750,753.500000,720.375000,696.812500,623.468750,618.187500,578.093750,488.937500
33,Mixed Rifle,932.181818,927.772727,887.727273,822.545455,831.863636,827.863636,832.181818,774.500000,808.090909,820.500000,733.454545,678.545455
34,Men's Cross Country,965.561905,889.955556,868.092063,869.552381,884.292063,885.276190,866.825397,845.441270,825.269841,818.485714,773.330159,775.790476
35,Men's Fencing,928.277778,861.222222,866.333333,809.166667,859.833333,786.277778,858.500000,795.388889,793.611111,803.555556,740.388889,614.777778
36,Men's Gymnastics,985.133333,844.066667,844.000000,902.466667,976.933333,977.866667,905.666667,989.933333,910.066667,964.200000,906.066667,899.000000
37,Women's Fencing,940.500000,831.227273,789.909091,791.863636,735.909091,690.045455,633.545455,690.409091,783.090909,745.863636,730.227273,740.363636

In [86]:
div1[div1['SPORT_NAME'].str.contains('Women')].groupby('SPORT_NAME')[['NCAA_CONFERENCE', 'FOURYEAR_SCORE']].mean().sort_values('FOURYEAR_SCORE',ascending=False).reset_index()[0:10]

              SPORT_NAME  FOURYEAR_SCORE
0           Women's Golf      991.569767
1     Women's Gymnastics      991.550000
2     Women's Ice Hockey      991.080000
3       Women's Lacrosse      989.862745
4         Women's Tennis      988.835962
5     Women's Water Polo      988.741935
6   Women's Field Hockey      988.144737
7       Women's Swimming      988.072165
8  Women's Cross Country      987.829412
9         Women's Skiing      987.750000

In [88]:
div1[(div1['SPORT_NAME'].str.contains('Men')) | (div1['SPORT_NAME'] == 'Baseball') | (div1['SPORT_NAME'] == 'Football')
    ].groupby('SPORT_NAME')[['NCAA_CONFERENCE', 'FOURYEAR_SCORE']].mean().sort_values('FOURYEAR_SCORE', ascending=False).reset_index()[0:10]

            SPORT_NAME  FOURYEAR_SCORE
0     Men's Ice Hockey      987.111111
1     Men's Water Polo      985.772727
2     Men's Gymnastics      985.133333
3     Men's Volleyball      984.095238
4         Men's Skiing      983.090909
5           Men's Golf      980.244898
6       Men's Swimming      979.654135
7       Men's Lacrosse      978.296875
8         Men's Tennis      977.984375
9  Men's Cross Country      972.206452

In [67]:
div1.groupby('SPORT_NAME')[cols].mean().sort_values('2014_SCORE', ascending=False).reset_index()[0:25]

,SPORT_NAME,FOURYEAR_SCORE,2014_SCORE,2013_SCORE,2012_SCORE,2011_SCORE,2010_SCORE,2009_SCORE,2008_SCORE,2007_SCORE,2006_SCORE,2005_SCORE,2004_SCORE
0,Women's Ice Hockey,991.080000,994.480000,946.160000,945.320000,946.160000,948.680000,944.720000,902.280000,894.760000,852.200000,767.720000,761.120000
1,Men's Skiing,983.090909,993.727273,976.909091,980.000000,879.000000,977.909091,871.636364,966.000000,969.454545,966.727273,959.454545,874.090909
2,Women's Gymnastics,991.550000,992.566667,992.933333,988.316667,987.500000,990.116667,989.250000,987.916667,985.083333,982.616667,981.516667,982.100000
3,Women's Lacrosse,989.862745,990.078431,956.950980,880.803922,860.049020,836.490196,819.245098,773.098039,730.333333,718.901961,686.058824,664.500000
4,Women's Field Hockey,988.144737,988.565789,984.657895,987.539474,975.105263,975.539474,962.407895,946.513158,939.894737,925.855263,927.421053,911.105263
5,Men's Volleyball,984.095238,988.047619,985.333333,975.904762,977.619048,983.190476,977.095238,924.000000,925.571429,857.380952,816.142857,800.142857
6,Men's Ice Hockey,987.111111,987.861111,985.138889,957.277778,954.500000,958.111111,949.916667,954.444444,947.277778,945.361111,946.472222,913.916667
7,Women's Soccer,984.112150,985.987539,973.532710,972.825545,971.507788,968.953271,959.236760,940.884735,924.077882,904.719626,874.728972,868.922118
8,Women's Volleyball,983.532110,985.813456,981.455657,980.730887,975.880734,975.516820,972.828746,951.651376,932.605505,916.559633,897.972477,895.862385
9,"Women's Track, Outdoor",981.969231,983.621538,967.338462,966.344615,951.809231,950.433846,941.098462,917.806154,909.963077,894.018462,857.913846,844.120000
10,Women's Skiing,987.750000,983.500000,991.416667,988.916667,981.166667,993.916667,985.833333,878.333333,998.416667,958.916667,879.750000,888.750000
11,Women's Softball,981.142857,981.937282,982.714286,974.564460,975.188153,973.693380,962.620209,937.965157,912.108014,889.369338,858.163763,858.334495
12,Women's Basketball,975.573099,980.125731,974.500000,974.064327,971.789474,969.871345,966.128655,947.739766,931.637427,918.345029,896.567251,894.377193
13,"Women's Track, Indoor",980.484076,979.382166,958.923567,964.324841,955.697452,954.777070,948.366242,915.006369,896.493631,882.550955,866.837580,856.863057
14,Women's Swimming,988.072165,978.664948,970.438144,971.283505,973.443299,965.402062,956.680412,908.711340,907.061856,884.350515,874.402062,862.479381
15,Women's Golf,991.569767,976.174419,965.279070,944.019380,928.779070,925.844961,899.523256,864.817829,809.453488,797.875969,759.798450,739.604651
16,Men's Soccer,971.395939,975.583756,970.411168,970.573604,965.771574,969.020305,957.269036,940.634518,916.142132,898.390863,872.822335,872.928934
17,Men's Wrestling,965.845070,970.591549,936.084507,950.338028,942.239437,945.056338,929.042254,948.591549,914.535211,898.690141,834.197183,841.760563
18,Baseball,969.506849,969.386986,968.585616,962.630137,964.534247,964.698630,952.849315,933.311644,901.273973,887.479452,861.181507,855.695205
19,Women's Cross Country,987.829412,965.055882,955.308824,956.405882,965.311765,966.602941,931.855882,919.535294,911.567647,900.788235,859.947059,854.947059
20,Men's Basketball,961.188953,964.406977,964.020349,960.366279,949.744186,949.796512,945.500000,927.953488,900.619186,886.982558,868.930233,866.639535
21,Football,956.299595,962.246964,946.384615,940.765182,923.663968,916.753036,914.226721,896.481781,882.372470,870.655870,855.769231,851.417004
22,"Men's Track, Indoor",969.448819,961.913386,927.688976,944.011811,930.917323,933.653543,933.051181,887.988189,863.429134,841.842520,818.574803,804.775591
23,Men's Lacrosse,978.296875,961.328125,893.593750,859.218750,853.468750,821.812500,805.000000,772.546875,754.234375,755.312500,771.484375,717.218750
24,Women's Tennis,988.835962,959.842271,960.107256,963.198738,938.539432,935.520505,941.716088,907.643533,880.088328,881.488959,850.548896,868.861199

In [39]:
ncaa.groupby('NCAA_CONFERENCE')[cols].mean().sort_values('2014_SCORE', ascending=False).reset_index()

,NCAA_CONFERENCE,FOURYEAR_SCORE,2014_SCORE,2013_SCORE,2012_SCORE,2011_SCORE,2010_SCORE,2009_SCORE,2008_SCORE,2007_SCORE,2006_SCORE,2005_SCORE,2004_SCORE
0,Northeast-10 Conference,996.666667,1000.000000,995.333333,995.666667,996.000000,990.000000,990.333333,968.666667,970.000000,968.666667,980.333333,992.666667
1,New England Women's and Men's Athletic Conference,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,-99.000000,-99.000000,-99.000000
2,Centennial Conference,990.000000,994.000000,986.333333,986.000000,993.666667,982.000000,979.000000,979.333333,994.666667,986.000000,986.000000,970.333333
3,Liberty League,990.181818,988.000000,988.818182,890.090909,893.454545,895.000000,889.727273,887.000000,880.000000,877.818182,492.727273,583.909091
4,The Ivy League,993.155462,988.000000,988.760504,987.878151,993.004202,994.004202,988.281513,984.470588,977.823529,988.915966,970.592437,965.449580
5,Southern Collegiate Athletic Conference,998.500000,988.000000,1000.000000,1000.000000,993.000000,987.000000,1000.000000,988.500000,994.500000,974.500000,1000.000000,994.000000
6,Big Ten Conference,984.938416,986.111437,982.956012,968.964809,968.108504,965.269795,960.519062,961.299120,954.178886,952.187683,946.633431,945.715543
7,Great Lakes Valley Conference,976.000000,983.000000,947.000000,994.000000,979.000000,977.000000,947.000000,971.000000,962.000000,828.000000,-99.000000,-99.000000
8,Peach Belt Conference,967.500000,982.750000,1000.000000,966.000000,917.500000,974.500000,1000.000000,968.750000,932.500000,931.000000,410.750000,441.000000
9,Northern Sun Intercollegiate Conference,980.750000,982.250000,979.000000,981.750000,979.750000,970.375000,974.625000,966.375000,965.000000,947.375000,946.375000,969.125000
10,Colonial Athletic Association,983.038251,980.759563,947.519126,968.765027,949.781421,943.808743,932.114754,954.327869,924.453552,922.437158,910.256831,915.087432
11,Metro Atlantic Athletic Conference,985.241706,979.601896,963.161137,942.417062,944.478673,944.886256,933.962085,917.492891,879.620853,925.753555,874.099526,837.203791
12,Big South Conference,976.243386,978.407407,964.037037,937.407407,919.185185,905.328042,909.126984,909.158730,811.730159,809.587302,727.206349,718.846561
13,Mid-American Conference,979.485981,977.018692,972.397196,974.523364,974.621495,977.084112,970.004673,966.210280,957.836449,961.504673,950.584112,953.018692
14,Ohio Valley Conference,977.685864,975.361257,970.167539,966.246073,967.303665,967.968586,952.319372,845.481675,847.910995,836.727749,825.209424,832.649215
15,Empire 8,985.000000,974.500000,1000.000000,993.000000,962.500000,961.000000,962.500000,975.000000,935.500000,952.500000,930.500000,967.000000
16,Mountain West Conference,977.735294,974.068627,951.215686,947.794118,951.700980,937.710784,942.093137,914.504902,902.573529,896.921569,892.960784,892.470588
17,Atlantic Coast Conference,985.356707,973.890244,960.225610,964.054878,955.250000,956.530488,963.018293,960.853659,963.536585,948.542683,937.716463,930.551829
18,Independent,973.277778,973.388889,974.611111,961.444444,971.555556,814.722222,849.277778,825.166667,802.666667,-41.722222,-99.000000,-99.000000
19,Great Northwest Athletic Conference,967.666667,973.333333,996.333333,943.666667,959.333333,959.333333,937.666667,951.000000,927.000000,906.000000,601.000000,578.666667
20,The Summit League,979.833333,972.448718,948.660256,945.262821,838.730769,832.737179,827.724359,705.397436,709.358974,701.692308,578.480769,455.564103
21,Pac-12 Conference,981.992032,971.940239,959.505976,957.195219,956.569721,959.573705,961.629482,952.872510,947.099602,941.741036,933.968127,913.605578
22,Southeastern Conference,981.136531,971.343173,974.398524,963.704797,964.000000,970.350554,958.597786,953.915129,955.568266,946.291513,939.140221,927.103321
23,Big West Conference,977.353293,971.251497,975.826347,962.502994,953.203593,959.323353,931.664671,935.000000,926.263473,908.904192,770.670659,768.946108
24,Great Lakes Intercollegiate Athletic Conference,981.250000,971.000000,980.000000,982.000000,984.250000,974.000000,994.500000,970.500000,959.750000,952.250000,965.250000,966.750000
25,Sun Belt Conference,972.531073,970.943503,956.841808,957.824859,943.661017,944.429379,949.446328,938.401130,928.576271,918.299435,910.254237,901.983051
26,Conference USA,975.300000,969.313043,965.004348,968.560870,959.856522,957.873913,949.226087,943.530435,938.843478,912.347826,916.130435,895.147826
27,Missouri Valley Conference,975.431250,967.750000,968.350000,973.725000,967.643750,963.562500,963.981250,954.987500,959.356250,931.837500,924.668750,943.162500
28,Big 12 Conference,976.927374,967.273743,971.921788,963.486034,971.335196,977.759777,969.407821,964.134078,954.273743,946.681564,941.000000,927.234637
29,Horizon League,971.931250,967.268750,954.118750,942.443750,932.281250,927.950000,912.075000,857.612500,863.193750,861.762500,828.681250,811.087500
30,Heartland Conference,973.000000,967.000000,962.000000,980.000000,981.000000,962.000000,969.000000,970.000000,948.000000,952.000000,-99.000000,-99.000000
31,American Athletic Conference,975.170854,964.522613,938.557789,934.728643,937.783920,940.733668,909.507538,893.758794,887.000000,868.793970,900.386935,904.477387
32,Western Athletic Conference,961.548872,962.924812,780.195489,789.812030,781.293233,775.135338,748.684211,592.413534,575.511278,360.676692,337.007519,349.984962
33,Pennsylvania State Athletic Conference,957.285714,961.142857,957.428571,961.142857,947.857143,964.000000,958.428571,970.714286,964.571429,924.142857,780.000000,789.428571
34,West Coast Conference,982.407186,960.940120,961.544910,948.940120,912.604790,929.634731,925.173653,907.455090,884.233533,880.544910,847.245509,806.694611
35,Atlantic 10 Conference,981.544402,959.606178,955.316602,967.482625,964.451737,957.779923,966.965251,969.335907,944.930502,929.019305,916.687259,922.814672
36,Gulf South Conference,948.000000,959.000000,957.000000,978.000000,908.000000,943.000000,957.000000,980.000000,947.000000,940.000000,940.000000,958.000000
37,Big East Conference,989.432584,954.365169,947.207865,949.837079,929.865169,926.185393,898.966292,899.022472,902.241573,899.078652,904.117978,878.112360
38,Southern Conference,972.449704,953.940828,924.550296,944.644970,929.130178,920.473373,922.035503,905.236686,880.402367,887.721893,842.041420,870.053254
39,Northeast Conference,982.025253,953.090909,940.550505,969.429293,945.808081,934.010101,927.287879,812.611111,802.489899,750.914141,751.262626,722.656566
40,America East Conference,982.476190,952.934524,864.720238,847.976190,847.440476,842.023810,847.708333,845.952381,834.136905,840.559524,820.732143,815.166667
41,Southland Conference,961.236715,952.637681,754.000000,724.705314,717.545894,716.695652,622.990338,609.285024,587.439614,500.961353,544.217391,548.371981
42,Atlantic Sun Conference,967.240602,951.248120,955.984962,797.105263,794.729323,788.180451,760.879699,750.909774,498.345865,496.473684,249.112782,257.789474
43,Big Sky Conference,970.304569,948.695431,928.375635,945.776650,958.670051,949.350254,930.573604,830.416244,802.984772,785.558376,692.137056,677.228426
44,Mid-Eastern Athletic Conference,953.642157,933.651961,938.901961,920.818627,889.485294,863.921569,887.328431,887.612745,791.308824,814.730392,801.049020,791.401961
45,East Coast Conference,935.000000,930.000000,936.000000,946.000000,930.000000,990.000000,959.000000,1000.000000,969.000000,967.000000,942.000000,909.000000
46,Southwestern Athletic Conference,955.463087,918.791946,904.664430,922.798658,894.671141,864.046980,863.677852,817.805369,853.416107,887.570470,842.751678,868.805369
47,Patriot League,982.756522,912.791304,906.465217,904.021739,905.169565,912.204348,886.360870,865.178261,850.578261,843.121739,814.447826,825.365217

In [40]:
ncaa[ncaa['NCAA_CONFERENCE'] == 'Northeast-10 Conference']

,SCHOOL_ID,SCHOOL_NAME,SCHOOL_TYPE,ACADEMIC_YEAR,SPORT_CODE,SPORT_NAME,NCAA_DIVISION,NCAA_SUBDIVISION,NCAA_CONFERENCE,FOURYEAR_ATHLETES,FOURYEAR_SCORE,FOURYEAR_ELIGIBILITY,FOURYEAR_RETENTION,2014_ATHLETES,2014_SCORE,2014_ELIGIBILITY,2014_RETENTION,2013_ATHLETES,2013_SCORE,2013_ELIGIBILITY,2013_RETENTION,2012_ATHLETES,2012_SCORE,2012_ELIGIBILITY,2012_RETENTION,2011_ATHLETES,2011_SCORE,2011_ELIGIBILITY,2011_RETENTION,2010_ATHLETES,2010_SCORE,2010_ELIGIBILITY,2010_RETENTION,2009_ATHLETES,2009_SCORE,2009_ELIGIBILITY,2009_RETENTION,2008_ATHLETES,2008_SCORE,2008_ELIGIBILITY,2008_RETENTION,2007_ATHLETES,2007_SCORE,2007_ELIGIBILITY,2007_RETENTION,2006_ATHLETES,2006_SCORE,2006_ELIGIBILITY,2006_RETENTION,2005_ATHLETES,2005_SCORE,2005_ELIGIBILITY,2005_RETENTION,2004_ATHLETES,2004_SCORE,2004_ELIGIBILITY,2004_RETENTION
2519,164447,American International College,1,2014,8,Men's Ice Hockey,2,-99,Northeast-10 Conference,72,993,0.9931,0.9929,18,1000,1.0,1.0,18,986,0.9722,1.0,19,987,1.0,0.9737,17,1000,1.0,1.000,16,984,1.0,0.9688,14,982,1.0000,0.9643,16,967,1.00,0.9333,15,1000,1.0000,1.0000,14,982,1.00,0.9643,14,1000,1.0000,1.0000,13,1000,1.0000,1.0000
2520,164739,Bentley University,1,2014,8,Men's Ice Hockey,2,-99,Northeast-10 Conference,75,997,1.0000,0.9933,19,1000,1.0,1.0,17,1000,1.0000,1.0,19,1000,1.0,1.0000,20,988,1.0,0.975,19,986,1.0,0.9730,19,1000,1.0000,1.0000,20,1000,1.00,1.0000,18,972,0.9722,0.9722,16,984,1.00,0.9688,17,985,1.0000,0.9706,16,1000,1.0000,1.0000
2668,166850,Merrimack College,1,2014,8,Men's Ice Hockey,2,-99,Northeast-10 Conference,92,1000,1.0000,1.0000,23,1000,1.0,1.0,24,1000,1.0000,1.0,22,1000,1.0,1.0000,23,1000,1.0,1.000,22,1000,1.0,1.0000,25,989,0.9796,1.0000,25,939,0.94,0.9375,21,938,0.9500,0.9250,26,940,0.96,0.9200,23,956,0.9556,0.9556,23,978,0.9778,0.9778

In [85]:
div1.groupby('NCAA_CONFERENCE')[['NCAA_CONFERENCE', 'FOURYEAR_SCORE']].mean().sort_values('FOURYEAR_SCORE', ascending=False).reset_index()[0:10]

                      NCAA_CONFERENCE  FOURYEAR_SCORE
0                      The Ivy League      993.155462
1                 Big East Conference      989.432584
2           Atlantic Coast Conference      985.356707
3  Metro Atlantic Athletic Conference      985.241706
4                  Big Ten Conference      984.938416
5       Colonial Athletic Association      983.038251
6                      Patriot League      982.756522
7               West Coast Conference      982.407186
8                Northeast Conference      982.025253
9                   Pac-12 Conference      981.992032

In [54]:
for i in cols:
    print div1.groupby('NCAA_CONFERENCE')[cols].mean().sort_values(i, ascending=False).reset_index()[0:10]

                      NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0                      The Ivy League      993.155462  988.000000  988.760504
1                 Big East Conference      989.432584  954.365169  947.207865
2           Atlantic Coast Conference      985.356707  973.890244  960.225610
3  Metro Atlantic Athletic Conference      985.241706  979.601896  963.161137
4                  Big Ten Conference      984.938416  986.111437  982.956012
5       Colonial Athletic Association      983.038251  980.759563  947.519126
6                      Patriot League      982.756522  912.791304  906.465217
7               West Coast Conference      982.407186  960.940120  961.544910
8                Northeast Conference      982.025253  953.090909  940.550505
9                   Pac-12 Conference      981.992032  971.940239  959.505976

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  949.837079  929.865169  926.185393  898.966292  899.022472  902.241573
2  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585
3  942.417062  944.478673  944.886256  933.962085  917.492891  879.620853
4  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
5  968.765027  949.781421  943.808743  932.114754  954.327869  924.453552
6  904.021739  905.169565  912.204348  886.360870  865.178261  850.578261
7  948.940120  912.604790  929.634731  925.173653  907.455090  884.233533
8  969.429293  945.808081  934.010101  927.287879  812.611111  802.489899
9  957.195219  956.569721  959.573705  961.629482  952.872510  947.099602

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  899.078652  904.117978  878.112360
2  948.542683  937.716463  930.551829
3  925.753555  874.099526  837.203791
4  952.187683  946.633431  945.715543
5  922.437158  910.256831  915.087432
6  843.121739  814.447826  825.365217
7  880.544910  847.245509  806.694611
8  750.914141  751.262626  722.656566
9  941.741036  933.968127  913.605578
                      NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0                      The Ivy League      993.155462  988.000000  988.760504
1                  Big Ten Conference      984.938416  986.111437  982.956012
2       Colonial Athletic Association      983.038251  980.759563  947.519126
3  Metro Atlantic Athletic Conference      985.241706  979.601896  963.161137
4                Big South Conference      976.243386  978.407407  964.037037
5             Mid-American Conference      979.485981  977.018692  972.397196
6         Western Athletic Conference      968.955357  975.705357  945.044643
7              Ohio Valley Conference      977.685864  975.361257  970.167539
8            Mountain West Conference      977.735294  974.068627  951.215686
9           Atlantic Coast Conference      985.356707  973.890244  960.225610

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
2  968.765027  949.781421  943.808743  932.114754  954.327869  924.453552
3  942.417062  944.478673  944.886256  933.962085  917.492891  879.620853
4  937.407407  919.185185  905.328042  909.126984  909.158730  811.730159
5  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
6  956.464286  946.348214  939.035714  907.625000  722.053571  701.982143
7  966.246073  967.303665  967.968586  952.319372  845.481675  847.910995
8  947.794118  951.700980  937.710784  942.093137  914.504902  902.573529
9  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  952.187683  946.633431  945.715543
2  922.437158  910.256831  915.087432
3  925.753555  874.099526  837.203791
4  809.587302  727.206349  718.846561
5  961.504673  950.584112  953.018692
6  446.866071  418.758929  434.169643
7  836.727749  825.209424  832.649215
8  896.921569  892.960784  892.470588
9  948.542683  937.716463  930.551829
              NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0              The Ivy League      993.155462  988.000000  988.760504
1          Big Ten Conference      984.938416  986.111437  982.956012
2         Big West Conference      977.353293  971.251497  975.826347
3                 Independent      973.277778  973.388889  974.611111
4     Southeastern Conference      981.136531  971.343173  974.398524
5     Mid-American Conference      979.485981  977.018692  972.397196
6           Big 12 Conference      976.927374  967.273743  971.921788
7      Ohio Valley Conference      977.685864  975.361257  970.167539
8  Missouri Valley Conference      975.431250  967.750000  968.350000
9              Conference USA      975.300000  969.313043  965.004348

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
2  962.502994  953.203593  959.323353  931.664671  935.000000  926.263473
3  961.444444  971.555556  814.722222  849.277778  825.166667  802.666667
4  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
5  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
6  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
7  966.246073  967.303665  967.968586  952.319372  845.481675  847.910995
8  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
9  968.560870  959.856522  957.873913  949.226087  943.530435  938.843478

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  952.187683  946.633431  945.715543
2  908.904192  770.670659  768.946108
3  -41.722222  -99.000000  -99.000000
4  946.291513  939.140221  927.103321
5  961.504673  950.584112  953.018692
6  946.681564  941.000000  927.234637
7  836.727749  825.209424  832.649215
8  931.837500  924.668750  943.162500
9  912.347826  916.130435  895.147826
                 NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0                 The Ivy League      993.155462  988.000000  988.760504
1        Mid-American Conference      979.485981  977.018692  972.397196
2     Missouri Valley Conference      975.431250  967.750000  968.350000
3           Northeast Conference      982.025253  953.090909  940.550505
4             Big Ten Conference      984.938416  986.111437  982.956012
5  Colonial Athletic Association      983.038251  980.759563  947.519126
6                 Conference USA      975.300000  969.313043  965.004348
7         Atlantic 10 Conference      981.544402  959.606178  955.316602
8         Ohio Valley Conference      977.685864  975.361257  970.167539
9      Atlantic Coast Conference      985.356707  973.890244  960.225610

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
2  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
3  969.429293  945.808081  934.010101  927.287879  812.611111  802.489899
4  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
5  968.765027  949.781421  943.808743  932.114754  954.327869  924.453552
6  968.560870  959.856522  957.873913  949.226087  943.530435  938.843478
7  967.482625  964.451737  957.779923  966.965251  969.335907  944.930502
8  966.246073  967.303665  967.968586  952.319372  845.481675  847.910995
9  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  961.504673  950.584112  953.018692
2  931.837500  924.668750  943.162500
3  750.914141  751.262626  722.656566
4  952.187683  946.633431  945.715543
5  922.437158  910.256831  915.087432
6  912.347826  916.130435  895.147826
7  929.019305  916.687259  922.814672
8  836.727749  825.209424  832.649215
9  948.542683  937.716463  930.551829
              NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0              The Ivy League      993.155462  988.000000  988.760504
1     Mid-American Conference      979.485981  977.018692  972.397196
2                 Independent      973.277778  973.388889  974.611111
3           Big 12 Conference      976.927374  967.273743  971.921788
4          Big Ten Conference      984.938416  986.111437  982.956012
5  Missouri Valley Conference      975.431250  967.750000  968.350000
6      Ohio Valley Conference      977.685864  975.361257  970.167539
7      Atlantic 10 Conference      981.544402  959.606178  955.316602
8     Southeastern Conference      981.136531  971.343173  974.398524
9              Conference USA      975.300000  969.313043  965.004348

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
2  961.444444  971.555556  814.722222  849.277778  825.166667  802.666667
3  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
4  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
5  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
6  966.246073  967.303665  967.968586  952.319372  845.481675  847.910995
7  967.482625  964.451737  957.779923  966.965251  969.335907  944.930502
8  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
9  968.560870  959.856522  957.873913  949.226087  943.530435  938.843478

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  961.504673  950.584112  953.018692
2  -41.722222  -99.000000  -99.000000
3  946.681564  941.000000  927.234637
4  952.187683  946.633431  945.715543
5  931.837500  924.668750  943.162500
6  836.727749  825.209424  832.649215
7  929.019305  916.687259  922.814672
8  946.291513  939.140221  927.103321
9  912.347826  916.130435  895.147826
              NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0              The Ivy League      993.155462  988.000000  988.760504
1           Big 12 Conference      976.927374  967.273743  971.921788
2     Mid-American Conference      979.485981  977.018692  972.397196
3     Southeastern Conference      981.136531  971.343173  974.398524
4      Ohio Valley Conference      977.685864  975.361257  970.167539
5          Big Ten Conference      984.938416  986.111437  982.956012
6  Missouri Valley Conference      975.431250  967.750000  968.350000
7           Pac-12 Conference      981.992032  971.940239  959.505976
8         Big West Conference      977.353293  971.251497  975.826347
9              Conference USA      975.300000  969.313043  965.004348

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
2  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
3  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
4  966.246073  967.303665  967.968586  952.319372  845.481675  847.910995
5  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
6  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
7  957.195219  956.569721  959.573705  961.629482  952.872510  947.099602
8  962.502994  953.203593  959.323353  931.664671  935.000000  926.263473
9  968.560870  959.856522  957.873913  949.226087  943.530435  938.843478

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  946.681564  941.000000  927.234637
2  961.504673  950.584112  953.018692
3  946.291513  939.140221  927.103321
4  836.727749  825.209424  832.649215
5  952.187683  946.633431  945.715543
6  931.837500  924.668750  943.162500
7  941.741036  933.968127  913.605578
8  908.904192  770.670659  768.946108
9  912.347826  916.130435  895.147826
              NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0              The Ivy League      993.155462  988.000000  988.760504
1     Mid-American Conference      979.485981  977.018692  972.397196
2           Big 12 Conference      976.927374  967.273743  971.921788
3      Atlantic 10 Conference      981.544402  959.606178  955.316602
4  Missouri Valley Conference      975.431250  967.750000  968.350000
5   Atlantic Coast Conference      985.356707  973.890244  960.225610
6           Pac-12 Conference      981.992032  971.940239  959.505976
7          Big Ten Conference      984.938416  986.111437  982.956012
8     Southeastern Conference      981.136531  971.343173  974.398524
9      Ohio Valley Conference      977.685864  975.361257  970.167539

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
2  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
3  967.482625  964.451737  957.779923  966.965251  969.335907  944.930502
4  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
5  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585
6  957.195219  956.569721  959.573705  961.629482  952.872510  947.099602
7  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
8  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
9  966.246073  967.303665  967.968586  952.319372  845.481675  847.910995

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  961.504673  950.584112  953.018692
2  946.681564  941.000000  927.234637
3  929.019305  916.687259  922.814672
4  931.837500  924.668750  943.162500
5  948.542683  937.716463  930.551829
6  941.741036  933.968127  913.605578
7  952.187683  946.633431  945.715543
8  946.291513  939.140221  927.103321
9  836.727749  825.209424  832.649215
                 NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0                 The Ivy League      993.155462  988.000000  988.760504
1         Atlantic 10 Conference      981.544402  959.606178  955.316602
2        Mid-American Conference      979.485981  977.018692  972.397196
3              Big 12 Conference      976.927374  967.273743  971.921788
4             Big Ten Conference      984.938416  986.111437  982.956012
5      Atlantic Coast Conference      985.356707  973.890244  960.225610
6     Missouri Valley Conference      975.431250  967.750000  968.350000
7  Colonial Athletic Association      983.038251  980.759563  947.519126
8        Southeastern Conference      981.136531  971.343173  974.398524
9              Pac-12 Conference      981.992032  971.940239  959.505976

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  967.482625  964.451737  957.779923  966.965251  969.335907  944.930502
2  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
3  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
4  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
5  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585
6  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
7  968.765027  949.781421  943.808743  932.114754  954.327869  924.453552
8  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
9  957.195219  956.569721  959.573705  961.629482  952.872510  947.099602

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  929.019305  916.687259  922.814672
2  961.504673  950.584112  953.018692
3  946.681564  941.000000  927.234637
4  952.187683  946.633431  945.715543
5  948.542683  937.716463  930.551829
6  931.837500  924.668750  943.162500
7  922.437158  910.256831  915.087432
8  946.291513  939.140221  927.103321
9  941.741036  933.968127  913.605578
              NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0              The Ivy League      993.155462  988.000000  988.760504
1   Atlantic Coast Conference      985.356707  973.890244  960.225610
2  Missouri Valley Conference      975.431250  967.750000  968.350000
3     Mid-American Conference      979.485981  977.018692  972.397196
4     Southeastern Conference      981.136531  971.343173  974.398524
5           Big 12 Conference      976.927374  967.273743  971.921788
6          Big Ten Conference      984.938416  986.111437  982.956012
7           Pac-12 Conference      981.992032  971.940239  959.505976
8      Atlantic 10 Conference      981.544402  959.606178  955.316602
9              Conference USA      975.300000  969.313043  965.004348

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585
2  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
3  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
4  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
5  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
6  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
7  957.195219  956.569721  959.573705  961.629482  952.872510  947.099602
8  967.482625  964.451737  957.779923  966.965251  969.335907  944.930502
9  968.560870  959.856522  957.873913  949.226087  943.530435  938.843478

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580
1  948.542683  937.716463  930.551829
2  931.837500  924.668750  943.162500
3  961.504673  950.584112  953.018692
4  946.291513  939.140221  927.103321
5  946.681564  941.000000  927.234637
6  952.187683  946.633431  945.715543
7  941.741036  933.968127  913.605578
8  929.019305  916.687259  922.814672
9  912.347826  916.130435  895.147826
              NCAA_CONFERENCE  FOURYEAR_SCORE  2014_SCORE  2013_SCORE  \
0              The Ivy League      993.155462  988.000000  988.760504
1     Mid-American Conference      979.485981  977.018692  972.397196
2          Big Ten Conference      984.938416  986.111437  982.956012
3   Atlantic Coast Conference      985.356707  973.890244  960.225610
4           Big 12 Conference      976.927374  967.273743  971.921788
5     Southeastern Conference      981.136531  971.343173  974.398524
6           Pac-12 Conference      981.992032  971.940239  959.505976
7     America East Conference      981.532895  950.019737  959.072368
8  Missouri Valley Conference      975.431250  967.750000  968.350000
9      Atlantic 10 Conference      981.544402  959.606178  955.316602

   2012_SCORE  2011_SCORE  2010_SCORE  2009_SCORE  2008_SCORE  2007_SCORE  \
0  987.878151  993.004202  994.004202  988.281513  984.470588  977.823529
1  974.523364  974.621495  977.084112  970.004673  966.210280  957.836449
2  968.964809  968.108504  965.269795  960.519062  961.299120  954.178886
3  964.054878  955.250000  956.530488  963.018293  960.853659  963.536585
4  963.486034  971.335196  977.759777  969.407821  964.134078  954.273743
5  963.704797  964.000000  970.350554  958.597786  953.915129  955.568266
6  957.195219  956.569721  959.573705  961.629482  952.872510  947.099602
7  940.565789  939.986842  934.065789  940.190789  938.190789  925.394737
8  973.725000  967.643750  963.562500  963.981250  954.987500  959.356250
9  967.482625  964.451737  957.779923  966.965251  969.335907  944.930502

   2006_SCORE  2005_SCORE  2004_SCORE
0  988.915966  970.592437  965.449580

In [59]:
ncaa[ncaa['2014_SCORE'] != -99].describe()

,SCHOOL_ID,SCHOOL_TYPE,ACADEMIC_YEAR,SPORT_CODE,NCAA_DIVISION,NCAA_SUBDIVISION,FOURYEAR_ATHLETES,FOURYEAR_SCORE,FOURYEAR_ELIGIBILITY,FOURYEAR_RETENTION,2014_ATHLETES,2014_SCORE,2014_ELIGIBILITY,2014_RETENTION,2013_ATHLETES,2013_SCORE,2013_ELIGIBILITY,2013_RETENTION,2012_ATHLETES,2012_SCORE,2012_ELIGIBILITY,2012_RETENTION,2011_ATHLETES,2011_SCORE,2011_ELIGIBILITY,2011_RETENTION,2010_ATHLETES,2010_SCORE,2010_ELIGIBILITY,2010_RETENTION,2009_ATHLETES,2009_SCORE,2009_ELIGIBILITY,2009_RETENTION,2008_ATHLETES,2008_SCORE,2008_ELIGIBILITY,2008_RETENTION,2007_ATHLETES,2007_SCORE,2007_ELIGIBILITY,2007_RETENTION,2006_ATHLETES,2006_SCORE,2006_ELIGIBILITY,2006_RETENTION,2005_ATHLETES,2005_SCORE,2005_ELIGIBILITY,2005_RETENTION,2004_ATHLETES,2004_SCORE,2004_ELIGIBILITY,2004_RETENTION
count,6418.000000,6418.000000,6418.0,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000
mean,179390.809598,0.347928,2014.0,19.520411,1.027267,-0.583983,77.266594,979.252415,0.978227,0.971933,19.924431,979.924743,0.982314,0.974527,17.140231,953.905890,-1.294549,-1.301241,16.306638,946.498598,-1.841696,-1.848064,15.360393,936.760050,-2.499993,-2.503765,14.807417,931.596915,-2.874901,-2.878792,13.736211,922.576971,-3.655194,-3.657608,11.444064,900.054534,-5.589021,-5.590800,9.729511,880.040355,-6.884593,-6.893067,8.326114,864.748676,-8.101707,-8.109790,5.012309,835.893425,-10.780442,-10.789041,3.872234,827.953412,-11.541980,-11.552400
std,41901.400836,0.476350,0.0,11.879780,0.180137,15.554342,62.723623,19.231986,0.026269,0.024448,16.032636,28.240642,0.033142,0.036064,23.666063,163.016348,14.908265,14.907249,25.098896,180.596509,16.552601,16.551517,26.579678,199.099005,18.310238,18.309519,27.429278,209.077805,19.232798,19.232011,29.063017,227.764110,21.003850,21.003308,32.891367,267.037838,24.751784,24.751304,35.040706,288.458528,26.893136,26.890658,37.129525,306.963813,28.707414,28.704857,40.767382,343.418975,32.190167,32.187030,41.545451,352.827039,33.076293,33.072351
min,100654.000000,0.000000,2014.0,1.000000,1.000000,-99.000000,4.000000,839.000000,0.774700,0.800000,4.000000,696.000000,0.571400,0.625000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,145813.000000,0.000000,2014.0,9.000000,1.000000,1.000000,40.000000,969.000000,0.968800,0.959225,11.000000,968.000000,0.972250,0.958300,10.000000,964.000000,0.963600,0.953100,10.000000,960.000000,0.961500,0.950000,10.000000,956.000000,0.952400,0.945525,10.000000,955.000000,0.952175,0.944400,9.000000,953.000000,0.947400,0.942900,9.000000,946.000000,0.938400,0.936350,9.000000,932.000000,0.928600,0.920000,9.000000,927.000000,0.923100,0.913000,8.000000,920.000000,0.916700,0.905400,8.000000,917.000000,0.916700,0.900000
50%,185572.000000,0.000000,2014.0,19.000000,1.000000,2.000000,59.000000,984.000000,0.985550,0.977900,15.000000,989.000000,1.000000,1.000000,15.000000,987.000000,1.000000,0.983300,15.000000,985.000000,1.000000,0.981800,15.000000,982.000000,1.000000,0.979200,15.000000,981.000000,1.000000,0.978300,14.000000,980.000000,1.000000,0.977800,14.000000,977.000000,0.983450,0.974100,14.000000,969.000000,0.979600,0.961500,14.000000,966.000000,0.975700,0.958300,13.000000,963.000000,0.970700,0.956500,13.000000,964.000000,0.976200,0.954600
75%,215763.250000,1.000000,2014.0,31.000000,1.000000,2.000000,95.000000,994.000000,1.000000,0.989500,24.000000,1000.000000,1.000000,1.000000,24.000000,1000.000000,1.000000,1.000000,24.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,23.000000,1000.000000,1.000000,1.000000,22.000000,1000.000000,1.000000,1.000000,21.000000,1000.000000,1.000000,1.000000,21.000000,995.000000,1.000000,1.000000,20.000000,1000.000000,1.000000,1.000000
max,433660.000000,1.000000,2014.0,38.000000,3.000000,3.000000,452.000000,1000.000000,1.000000,1.000000,145.000000,1000.000000,1.000000,1.000000,112.000000,1000.000000,1.000000,1.000000,113.000000,1000.000000,1.000000,1.000000,114.000000,1000.000000,1.000000,1.000000,120.000000,1000.000000,1.000000,1.000000,121.000000,1000.000000,1.000000,1.000000,125.000000,1000.000000,1.000000,1.000000,129.000000,1000.000000,1.000000,1.000000,209.000000,1000.000000,1.000000,1.000000,179.000000,1000.000000,1.000000,1.000000,123.000000,1000.000000,1.000000,1.000000

In [73]:
ncaa[(ncaa['2014_SCORE'] != -99) & (ncaa['2014_SCORE'] < 930)][cols].sort_values('2014_SCORE')

,FOURYEAR_SCORE,2014_SCORE,2013_SCORE,2012_SCORE,2011_SCORE,2010_SCORE,2009_SCORE,2008_SCORE,2007_SCORE,2006_SCORE,2005_SCORE,2004_SCORE
304,847,696,848,938,900,917,957,923,840,-99,-99,-99
1158,967,714,1000,955,1000,1000,938,875,1000,917,786,1000
1152,863,718,955,861,950,-99,895,-99,917,1000,972,944
2895,966,750,1000,950,960,1000,1000,1000,1000,909,958,1000
5628,914,750,-99,700,1000,909,-99,-99,667,938,667,857
2869,839,760,942,854,800,977,917,940,929,966,886,1000
1155,869,778,942,827,1000,895,841,946,931,1000,924,920
1156,882,778,979,841,1000,941,847,946,926,1000,924,920
1432,909,788,900,1000,958,885,813,952,950,900,853,864
1005,974,792,1000,929,1000,974,971,955,964,907,944,750
5441,923,794,953,967,973,934,1000,987,981,893,913,950
11,921,800,968,969,952,969,906,940,1000,962,875,913
1438,964,800,950,1000,938,929,941,929,947,889,950,1000
2238,935,808,-99,-99,-99,-99,-99,-99,-99,-99,867,-99
2179,939,818,973,1000,939,974,961,900,957,833,917,804
1465,975,824,1000,-99,1000,929,1000,1000,964,1000,964,938
2175,918,825,891,962,964,1000,983,960,1000,983,978,946
4035,975,833,-99,950,-99,786,938,900,-99,1000,935,1000
2276,952,833,1000,1000,966,1000,1000,1000,1000,906,933,944
1153,947,833,917,900,1000,889,1000,1000,-99,938,938,1000
3406,942,838,1000,931,983,1000,978,844,967,958,-99,-99
207,903,838,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
208,903,838,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
1919,951,844,971,1000,1000,964,923,926,962,958,1000,1000
2652,947,849,975,1000,917,1000,983,972,1000,875,975,980
4019,977,850,920,1000,1000,1000,972,950,972,941,1000,969
3541,932,850,-99,789,1000,962,923,1000,1000,977,1000,964
2242,944,850,1000,-99,-99,-99,-99,-99,-99,-99,880,897
6232,958,850,933,1000,1000,1000,850,1000,-99,1000,-99,929
837,979,850,-99,950,1000,-99,-99,-99,-99,-99,929,1000
...,...,...,...,...,...,...,...,...,...,...,...,...
848,974,926,1000,1000,972,1000,1000,917,1000,1000,-99,875
5675,947,926,951,952,960,912,955,939,955,940,955,934
4348,954,926,944,976,973,949,981,949,970,1000,981,949
349,946,926,938,957,964,971,894,891,870,-99,-99,-99
1996,954,926,966,959,967,924,964,928,960,927,971,973
866,992,926,1000,1000,-99,1000,1000,1000,923,912,929,893
200,962,926,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99
1338,957,927,930,983,984,1000,948,964,914,956,971,984
5870,963,928,950,977,995,960,945,962,898,949,994,964
4844,948,928,958,945,960,951,975,908,873,904,967,969
1119,976,929,979,1000,1000,1000,1000,833,896,958,-99,-99
2305,950,929,1000,935,935,962,944,1000,1000,1000,1000,1000
5515,942,929,966,963,914,1000,981,980,1000,1000,923,1000
5187,948,929,927,956,982,897,912,1000,979,963,1000,1000
5497,948,929,976,944,944,1000,1000,950,974,816,971,912
3356,979,929,980,1000,1000,976,965,986,1000,968,953,988
1936,946,929,931,1000,917,971,968,979,934,910,932,935
1421,953,929,968,1000,917,963,1000,1000,964,1000,1000,1000
5386,954,929,1000,950,938,1000,897,958,900,885,1000,969
2926,955,929,1000,1000,917,962,875,1000,969,977,925,917
167,953,929,976,929,987,957,982,926,958,925,911,883
2925,957,929,1000,1000,917,964,875,1000,969,1000,932,925
6393,982,929,1000,1000,1000,1000,950,979,1000,1000,1000,1000
1748,979,929,967,1000,1000,1000,933,943,1000,1000,1000,1000
1315,950,929,1000,1000,906,1000,1000,1000,1000,1000,933,1000
5949,933,929,951,912,939,950,934,976,805,861,882,869
5953,982,929,1000,1000,905,960,880,929,1000,833,893,968
5188,948,929,927,956,982,914,1000,1000,979,1000,1000,-99
2923,991,929,1000,1000,967,972,929,964,962,971,917,850
5203,985,929,1000,1000,929,893,967,964,-99,-99,-99,-99

In [72]:
teams = ncaa.groupby(['SCHOOL_NAME', 'SPORT_NAME'])[cols].mean().sort_values('2014_SCORE', ascending=False).reset_index()

In [76]:
teams['avg'] = (teams['2014_SCORE'] + teams['2013_SCORE'] + teams['2012_SCORE'] + teams['2011_SCORE'] + 
                teams['2010_SCORE'] + teams['2009_SCORE'] + teams['2008_SCORE'] + teams['2007_SCORE'] +
                teams['2006_SCORE'] + teams['2005_SCORE'] + teams['2004_SCORE']) / 11

In [90]:
teams[teams.avg == 1000][['SCHOOL_NAME', 'SPORT_NAME', 'avg']].sort_values('avg', ascending=False)

,SCHOOL_NAME,SPORT_NAME,avg
79,Monmouth University,Women's Tennis,1000.0
1925,Dartmouth College,Women's Tennis,1000.0
2027,College of the Holy Cross,Women's Cross Country,1000.0
2031,Columbia University-Barnard College,Men's Tennis,1000.0
2189,Yale University,Men's Tennis,1000.0
2205,Xavier University,Women's Tennis,1000.0
2221,Yale University,Women's Tennis,1000.0
2223,Yale University,Women's Softball,1000.0
2231,Yale University,Women's Gymnastics,1000.0
2232,Yale University,Women's Golf,1000.0
2254,Arizona State University,Women's Tennis,1000.0
2319,Brown University,Women's Fencing,1000.0
2322,Brown University,Women's Gymnastics,1000.0
2368,Bucknell University,Women's Soccer,1000.0
2383,Butler University,Women's Golf,1000.0
2386,Butler University,Women's Tennis,1000.0
2433,Boston College,Men's Skiing,1000.0
2463,Brown University,Men's Golf,1000.0
2480,Bowling Green State University,Women's Tennis,1000.0
2489,Bradley University,Women's Tennis,1000.0
2492,Duke University,Men's Golf,1000.0
2506,Fordham University,Women's Tennis,1000.0
2618,Elon University,Women's Cross Country,1000.0
2619,Elon University,Women's Golf,1000.0
2682,University of Pennsylvania,Women's Tennis,1000.0
2689,University of Pennsylvania,Women's Golf,1000.0
2722,Harvard University,Men's Golf,1000.0
2756,Harvard University,Women's Cross Country,1000.0
2783,Georgia Institute of Technology,Men's Golf,1000.0
1956,DePaul University,Women's Tennis,1000.0
...,...,...,...
306,Northwestern University,Men's Tennis,1000.0
1920,Dartmouth College,Women's Rowing,1000.0
310,Northwestern University,Women's Golf,1000.0
411,"University of Maine, Orono",Women's Cross Country,1000.0
490,"University of North Carolina, Chapel Hill",Women's Golf,1000.0
581,University of Notre Dame,Men's Cross Country,1000.0
584,University of Northern Iowa,Women's Volleyball,1000.0
609,University of Notre Dame,"Men's Track, Outdoor",1000.0
611,University of Notre Dame,"Men's Track, Indoor",1000.0
622,University of Notre Dame,Men's Golf,1000.0
627,Kent State University,Women's Cross Country,1000.0
697,Loyola University Maryland,"Women's Track, Outdoor",1000.0
722,Loyola University Chicago,Men's Cross Country,1000.0
738,Lafayette College,Women's Lacrosse,1000.0
741,Lafayette College,Women's Swimming,1000.0
818,Lehigh University,Women's Cross Country,1000.0
826,Lehigh University,Women's Volleyball,1000.0
1257,Princeton University,Women's Golf,1000.0
1259,Princeton University,Women's Lacrosse,1000.0
1346,Purdue University,Women's Volleyball,1000.0
1406,"University of Illinois, Champaign",Women's Golf,1000.0
1514,Santa Clara University,Women's Water Polo,1000.0
1618,University of Dayton,Men's Golf,1000.0
1728,Colgate University,Women's Swimming,1000.0
1877,Davidson College,Women's Soccer,1000.0
1908,Dartmouth College,Men's Golf,1000.0
1916,Dartmouth College,Women's Field Hockey,1000.0
1917,Dartmouth College,Women's Golf,1000.0
1919,Dartmouth College,Women's Lacrosse,1000.0
2834,Gonzaga University,Women's Golf,1000.0

In [82]:
team1000 = teams[teams.avg == 1000][['SCHOOL_NAME', 'SPORT_NAME', 'avg']].sort_values('avg', ascending=False)

In [83]:
team1000['SPORT_NAME'].value_counts()

Women's Tennis            11
Women's Golf              10
Men's Golf                 7
Women's Cross Country      6
Women's Lacrosse           3
Men's Tennis               3
Women's Swimming           3
Women's Volleyball         3
Women's Soccer             2
Women's Gymnastics         2
Men's Cross Country        2
Women's Field Hockey       1
Women's Softball           1
Women's Track, Outdoor     1
Women's Water Polo         1
Women's Fencing            1
Women's Rowing             1
Men's Skiing               1
Men's Track, Outdoor       1
Men's Track, Indoor        1
Name: SPORT_NAME, dtype: int64

In [91]:
team1000['SCHOOL_NAME'].value_counts()

Dartmouth College                            7
Yale University                              5
University of Notre Dame                     4
Brown University                             3
Princeton University                         2
Elon University                              2
Northwestern University                      2
Harvard University                           2
University of Pennsylvania                   2
Lafayette College                            2
Butler University                            2
Lehigh University                            2
Bucknell University                          1
Loyola University Chicago                    1
Purdue University                            1
University of Northern Iowa                  1
Bradley University                           1
University of North Carolina, Chapel Hill    1
Columbia University-Barnard College          1
Xavier University                            1
Colgate University                           1
Fordham University                           1
Santa Clara University                       1
University of Maine, Orono                   1
Gonzaga University                           1
Boston College                               1
Davidson College                             1
Loyola University Maryland                   1
Monmouth University                          1
College of the Holy Cross                    1
DePaul University                            1
Duke University                              1
Bowling Green State University               1
Arizona State University                     1
Kent State University                        1
University of Illinois, Champaign            1
Georgia Institute of Technology              1
University of Dayton                         1
Name: SCHOOL_NAME, dtype: int64